version: '3.8'

services:
  online-shopping:
    container_name: online-shopping
    build:
      context: .
      dockerfile: dockerfile
#    ports:
#      - "3000:3000"
    restart: unless-stopped
    networks:
      - bible-project-network

networks:
  bible-project-network:
    external: true
